---

# First, we check if the space already exist:

- name: "Configure SS: Check uuid for rclone space"
  mysql_query:
    login_db: "{{ archivematica_src_ss_db_name }}"
    login_user: "{{ archivematica_src_ss_db_user }}"
    login_password: "{{ archivematica_src_ss_db_password }}"
    login_host: "{{ archivematica_src_ss_db_host }}"
    query: >
      SELECT space_id from locations_rclone where remote_name = %(remote_name)s and container = %(container)s ;
    named_args:
      remote_name: "{{ remote_name }}"
      container: "{{ container }}"
  register: __rclone_uuid_query

# If an space with the same remote_name and container doesn't exist, we create it:
- name: "Configure rclone space"
  when: __rclone_uuid_query.rowcount[0] < 1
  block:
    - name: "Configure SS: Add rclone space"
      uri:
        url: "{{ archivematica_src_configure_ss_url }}/api/v2/space/"
        headers:
          Content-Type: "application/json"
          Authorization: "ApiKey {{ archivematica_src_configure_ss_user }}:{{ archivematica_src_configure_ss_api_key }}"
        body:
          access_protocol: RCLONE
          path: "/"
          staging_path: /var/archivematica/sharedDirectory/tmp
          remote_name: "{{ remote_name }}"
          container: "{{ container }}"
        body_format: json
        status_code: 201
        method: POST
      register: __rclone_space_creation

    # Once is created, we get the space's uuid (could be obtained from the JSON reply)
    - name: "Configure SS: Check uuid for rclone space"
      mysql_query:
        login_db: "{{ archivematica_src_ss_db_name }}"
        login_user: "{{ archivematica_src_ss_db_user }}"
        login_password: "{{ archivematica_src_ss_db_password }}"
        login_host: "{{ archivematica_src_ss_db_host }}"
        query: >
          SELECT space_id from locations_rclone where remote_name = %(remote_name)s and container = %(container)s limit 1;
        named_args:
          remote_name: "{{ remote_name }}"
          container: "{{ container }}"
      register: __rclone_uuid_space

   
    - name: "Configure SS remote pipeline: Set uuid for default filesystem space"
      set_fact:
         __rclone_space_uuid: "{{ (__rclone_uuid_space.query_result |flatten | first).space_id }}"

     # We create the location using the previously created space
    - name: "Configure SS: Add custom rclone location"
      uri:
        url: "{{ archivematica_src_configure_ss_url }}/api/v2/location/"
        headers:
          Content-Type: "application/json"
          Authorization: "ApiKey {{ archivematica_src_configure_ss_user }}:{{ archivematica_src_configure_ss_api_key }}"
        body:
          pipeline: ["/api/v2/pipeline/{{ pipeline_uuid.stdout }}/"]
          purpose: "{{ location_purpose }}"
          relative_path: "/"
          description: "{{ location_description }}"
          space: "/api/v2/space/{{ __rclone_space_uuid }}/"
          default: "{{ location_default }}"
        body_format: json
        status_code: 201
        method: POST

