---

###########################################################
#   4- Code install
###########################################################

- name: "Change archivematica-source owner to archivematica"
  file:
    dest: "{{ archivematica_src_dir }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
    recurse: "yes"

- name: "Install archivematica Python package"
  become: "yes"
  become_user: "archivematica"
  pip:
    virtualenv: "{{ archivematica_src_am_virtualenv }}"
    chdir: "{{ archivematica_src_dir }}/archivematica"
    name: .
    editable: yes
    extra_args: "--no-deps"

- name: "Copy gunicorn configuration file"
  copy:
    src: "{{ archivematica_src_dir }}/archivematica/src/archivematica/dashboard/install/dashboard.gunicorn-config.py"
    dest: "{{ archivematica_src_am_dashboard_gunicorn_config }}"
    backup: "yes"
    force: "yes"
    remote_src: "yes"
    mode: '0644'

#
# front-end
#

- name: "Install front-end dependencies"
  become: "yes"
  become_user: "archivematica"
  command: npm install
  args:
    chdir: "{{ item }}"
  with_items:
    - "{{ archivematica_src_dir }}/archivematica/src/archivematica/dashboard/frontend"

#
# update logging configuration (Archivematica 1.18.0)
#

- name: "Check if logging files exist"
  stat:
    path: "{{ item }}"
  register: logging_files_stats
  loop:
    - "/etc/archivematica/dashboard.logging.json"
    - "/etc/archivematica/serverConfig.logging.json"
    - "/etc/archivematica/clientConfig.logging.json"

- name: "Update the custom_handlers class path in logging files"
  replace:
    path: "{{ item.stat.path }}"
    regexp: '"class": "custom_handlers.GroupWriteRotatingFileHandler",$'
    replace: '"class": "archivematica.archivematicaCommon.custom_handlers.GroupWriteRotatingFileHandler",'
  when: item.stat.exists
  loop: "{{ logging_files_stats.results }}"

#
# collectstatic
#

- name: "Collect static files"
  shell: >
    {{ archivematica_src_am_virtualenv }}/bin/python -m archivematica.dashboard.manage
    collectstatic --noinput
  args:
    executable: /bin/bash
  environment: "{{ archivematica_src_am_dashboard_environment }}"

#
# compilemessages
#

- name: "Compile gettext po files (compilemessages)"
  shell: >
    {{ archivematica_src_am_virtualenv }}/bin/python -m archivematica.dashboard.manage
    compilemessages
  args:
    executable: /bin/bash
  environment: "{{ archivematica_src_am_dashboard_environment }}"
