---

# dashboard-configure

# Create api-key if not defined
- set_fact: archivematica_src_configure_am_api_key={{ 999999999999999999998 | random | to_uuid | hash('md5') }}
  when: archivematica_src_configure_am_api_key is undefined

- name: "Create Dashboard user and register pipeline on SS"
  django_manage:
    command: "install --username={{ archivematica_src_configure_am_user }} --password={{ archivematica_src_configure_am_password }} --email={{ archivematica_src_configure_am_email }} --org-name={{ archivematica_src_configure_am_org_name }} --org-id={{ archivematica_src_configure_am_org_id }} --api-key={{ archivematica_src_configure_am_api_key }} --ss-url={{ archivematica_src_configure_ss_url }} --ss-user={{ archivematica_src_configure_ss_user }} --ss-api-key={{ archivematica_src_configure_ss_api_key }} --whitelist={{archivematica_src_configure_am_whitelist}}"
    app_path: "{{ archivematica_src_am_dashboard_app }}"
    pythonpath: "{{ archivematica_src_am_common_app }}"
    virtualenv: "{{ archivematica_src_am_dashboard_virtualenv }}"
