---
###########################################################
#   2- python dependencies (pip packages)
###########################################################

- name: "Install archivematica-common pip dependencies"
  pip:
    requirements: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements.txt"
    state: "latest"

- name: "Install archivematica-dashboard pip dependencies"
  pip:
    requirements: "{{ archivematica_src_dir }}/archivematica/src/dashboard/src/requirements.txt"
    state: "latest"

- name: "Check if MCPClient requirements file exists"
  stat:
    path: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/requirements.txt"
  register: "requirements_file"

- name: "Install archivematica-mcp-client pip dependencies"
  pip:
    requirements: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/requirements.txt"
    state: "latest"
  when: "requirements_file.stat.exists is defined and requirements_file.stat.exists"
