###########################################################
#   6- web server config - when using gunicorn with nginx
###########################################################
- name: "Add storage service gunicorn systemd (/etc/systemd)"
  template:
    src: "etc/systemd/system/archivematica-storage-service.service.j2"
    dest: "/etc/systemd/system/archivematica-storage-service.service"
    backup: "yes"
  tags: "amsrc-ss-osconf"
  when:
    - ansible_service_mgr == "systemd"

- name: "Include systemd-creds config"
  include: systemd-creds.yml
  vars:
    service: archivematica-storage-service
    secret_name: ss
    credentials:
      SS_DB_URL: "mysql://{{ archivematica_src_ss_db_user }}:{{ archivematica_src_ss_db_password }}@{{ archivematica_src_ss_db_host }}:{{ archivematica_src_ss_db_port }}/{{ archivematica_src_ss_db_name }}"
      DJANGO_SECRET_KEY: "{{ archivematica_src_ss_django_secret_key }}"
  when: archivematica_src_systemd_credentials|bool

- name: "Add storage service gunicorn systemd env file"
  template:
    src: "etc/sysconfig/archivematica-storage-service.j2"
    dest: "{{ systemd_environment_path }}/archivematica-storage-service"
    backup: "yes"
  tags: "amsrc-ss-osconf"

#
# Configure logging
#

- name: "Config SS logging"
  template:
    src: "{{ item }}"
    dest: "/etc/archivematica/storageService.logging.json"
    backup: "yes"
  with_first_found:
    - files:
        - "templates/{{ inventory_hostname }}/storageService.logging.json.j2"
        - "templates/storageService.logging.json.j2"
        - "etc/archivematica/storageService.logging.json.j2"
  tags: "amsrc-ss-osconf"
  when: "archivematica_src_logging_backward_compatible|bool"

- name: "Remove SS backward-compatible logging"
  file:
    path: "/etc/archivematica/storageService.logging.json"
    state: "absent"
  when: "not archivematica_src_logging_backward_compatible|bool"

- name: "Configure rng-tools (Ubuntu < 22.04)"
  lineinfile:
    dest: "/etc/default/rng-tools"
    line: "HRNGDEVICE=/dev/urandom"
    insertafter: "^#HRNGDEVICE"
    state: "present"
  tags: "rng-tools"
  become: "yes"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int < 22

- name: "Configure rng-tools-debian (Ubuntu >= 22.04)"
  lineinfile:
    dest: "/etc/default/rng-tools-debian"
    line: "HRNGDEVICE=/dev/urandom"
    insertafter: "^#HRNGDEVICE"
    state: "present"
  tags: "rng-tools"
  become: "yes"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int >= 22

- name: "Start rng-tools (Ubuntu < 22.04)"
  service:
    name: "rng-tools"
    state: "restarted"
    enabled: "yes"
  tags: "rng-tools"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int < 22

- name: "Start rng-tools (Ubuntu >= 22.04)"
  service:
    name: "rng-tools-debian"
    state: "restarted"
    enabled: "yes"
  tags: "rng-tools"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int >= 22

- name: "Start rng-tools (RedHat/CentOS/Rocky)"
  service:
    name: "rngd"
    state: "restarted"
    enabled: "yes"
  tags: "rng-tools"
  when:
    - ansible_os_family in ['RedHat','Rocky']

- name: "Enable SS services (systemd)"
  service:
    name: "archivematica-storage-service"
    state: "restarted"
    enabled: "yes"
    daemon_reload: "yes"
  when:
    - ansible_service_mgr == "systemd"
  tags: "amsrc-ss-osconf"
