---

#######################################################################
# Install dependencies according to osdeps dicts
#######################################################################

# ubuntu block
- block:
    - name: "Install External dependency repo keys (Ubuntu)"
      apt_key:
        id: "{{ item.id }}"
        url: "{{ item.url }}"
        state: "present"
        validate_certs: "{{ item.validate_certs }}"
      with_items:
        - "{{ storage_service_osdeps.repokeys }}"
      when:
        - storage_service_osdeps.repokeys

    - name: "Add External dependency repos (Ubuntu)"
      apt_repository:
        repo: "{{ item }}"
        state: "present"
      with_items:
        - "{{ storage_service_osdeps.repos }}"
      when:
        - storage_service_osdeps.repos

  when:
    - ansible_distribution == "Ubuntu"
# End Ubuntu block

# Centos/RH block
- block:
    - name: "Add External repo keys (RH/CentOS/Rocky)"
      rpm_key:
        state: present
        key: "{{ item }}"
      with_items:
        - "{{ storage_service_osdeps.repokeys }}"
      when:
        - storage_service_osdeps.repokeys

    - name: "Add External dependency repos (RH/CentOS/Rocky)"
      yum_repository:
        name: "{{ item['name'] }}"
        description: "{{ item['description'] }}"
        baseurl: "{{ item['baseurl'] }}"
        gpgcheck: "{{ item['gpgcheck'] }}"
        enabled: "{{ item['enabled'] }}"
      with_items:
        - "{{ storage_service_osdeps.repos }}"
      when:
        - storage_service_osdeps.repos

  when:
    - ansible_os_family in ['RedHat','Rocky']
    - install_rpm_repositories|bool
# End RH/CentOS/Rocky block

# Not using package in next task because it is slower than apt or yum modules.
# The package module is not installing the every list of packages at the same time
# But yum or apt modules doesn't allow loops (deprecated) so the trick is using the
# install-packages.yml task file

- include_tasks: "install-packages.yml"
  vars:
    packages: "{{ item.packages }}"
    name: "{{ item.name }}"
  when:
    - item.packages|length>0
  loop:
    - { name: 'Storage Service osdeps 1', packages: "{{ storage_service_osdeps.packages | default([]) }}" }
    - { name: 'Storage Service osdeps 2', packages: "{{ storage_service_osdeps.packages_2 | default([]) }}" }
    - { name: 'Storage Service osdeps 3', packages: "{{ storage_service_osdeps.packages_3 | default([]) }}" }
