---

#
# Packages
#

- name: "Update apt packages cache"
  apt:
    update_cache: "yes"
    cache_valid_time: "300"

- name: "Install necessary packages"
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items:
    - "python-pycurl"
    - "git"

#
# Archivematica user
#

- name: "Create user archivematica"
  user:
    name: "archivematica"
    uid: "333"
    system: "yes"
    groups: "audio"
    home: "/var/lib/archivematica"

- name: "Add archivematica user permissions in visudo file"
  lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^archivematica ALL\\="
    line: "archivematica ALL=NOPASSWD:/bin/mv,/bin/chown,/bin/chmod,/usr/bin/find,/usr/bin/gs,/usr/bin/inkscape"
    validate: "/usr/sbin/visudo -cf %s"

#
# Sources container
#

- name: "Expand archivematica_src_dir"
  set_fact:
    archivematica_src_dir: "{{ archivematica_src_dir|expanduser }}"

- name: "Create archivematica_src_dir"
  file:
    state: "directory"
    path: "{{ archivematica_src_dir }}"

#
# Disable unneeded services
#

- name: "Disable unneeded services"
  service:
    name: "{{ item }}"
    state: "stopped"
    enabled: "no"
  when: "ansible_distribution_release == '14.04'"
  with_items:
    - "chef-client"
    - "puppet"
