---

- include: "includes/common.yml"

- name: "Add multiverse repositories"
  become: "yes"
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
    - "ppa:archivematica/externals-dev"

- name: "Install archivematica-mcp-client package dependencies"
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items: "{{ archivematica_src_am_mcpclient_pkgdeps }}"

- name: "Install clamav"
  include: "includes/clamav.yml"

- name: "Install archivematica-mcp-client virtualenv with upgraded pip"
  pip:
    name: "pip"
    virtualenv: "{{ archivematica_src_am_mcpclient_env_dir }}"
    state: "latest"

- name: "Install archivematica-mcp-client Python dependencies in virtualenv"
  pip:
    requirements: "{{ archivematica_src_am_mcpclient_src_dir }}/requirements.txt"
    virtualenv: "{{ archivematica_src_am_mcpclient_env_dir }}"
    state: "present"

- name: "Create archivematica-mcp-client log directory"
  file:
    dest: "{{ item }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
    mode: "g+s"
  with_items:
    - "/var/log/archivematica/MCPClient"

- name: "Install archivematica-mcp-client upstart service"
  template:
    src: "etc/init/archivematica-mcp-client.conf"
    dest: "/etc/init/archivematica-mcp-client.conf"
    backup: "yes"

- name: "Reload upstart"
  command: "initctl reload-configuration"

- name: "Create /etc/archivematica/MCPClient directory"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/etc/archivematica/MCPClient"
  notify:
    - "Restart archivematica-mcp-client"

- name: "Install MCPClient clientConfig.conf file"
  template:
    src: "etc/archivematica/MCPClient/clientConfig.conf"
    dest: "/etc/archivematica/MCPClient/clientConfig.conf"
    backup: "yes"
  notify:
    - "Restart archivematica-mcp-client"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "fits"
    - "archivematica-mcp-client"
