---

- include: "components/includes/common.yml"

- name: "Checkout Archivematica code"
  git:
    repo: "{{ archivematica_src_am_repo }}"
    dest: "{{ archivematica_src_dir }}/archivematica"
    version: "{{ archivematica_src_am_version }}"
    force: "yes"
    accept_hostkey: "yes"

- name: "Add multiverse repositories"
  become: "yes"
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
    - "ppa:archivematica/externals-dev"

- name: "Install archivematica-mcp-client package dependencies"
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items: "{{ archivematica_src_am_mcpclient_pkgdeps }}"

- name: "Install archivematica-mcp-client Python dependencies in virtualenv"
  pip:
    chdir: "{{ archivematica_src_dir }}/archivematica/src/archivematicaCommon/requirements"
    requirements: "requirements.txt"
    virtualenv: "/usr/share/python/archivematica-mcp-client"
    state: "latest"

- name: "Install archivematica-mcp-client Python dependencies in virtualenv"
  pip:
    chdir: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/requirements"
    requirements: "production.txt"
    virtualenv: "/usr/share/python/archivematica-mcp-client"
    state: "latest"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "started"
    enabled: "yes"
  with_items:
    - "fits"

- name: "Create archivematica-mcp-client log directories"
  file:
    dest: "{{ item }}"
    state: "directory"
    owner: "archivematica"
    group: "archivematica"
    mode: "g+s"
  with_items:
    - "/var/log/archivematica/MCPClient"

- name: "Create subdirectories for archivematica-mcp-client source files"
  file:
    dest: "{{ item }}"
    state: "directory"
  with_items:
    - "/etc/archivematica/MCPClient"
    - "/usr/lib/archivematica"

- include: "components/includes/clamav.yml"

- name: "Template archivematica-mcp-client init service file"
  template:
    src: "etc_init_archivematica-mcp-client.conf.j2"
    dest: "/etc/init/archivematica-mcp-client.conf"
    backup: "yes"

- name: "Reload Upstart configuration"
  command: "initctl reload-configuration"

- name: "Copy archivematica-mcp-client source files"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - src: "{{ archivematica_src_dir }}/archivematica/src/MCPClient/lib/"
      dest: "/usr/lib/archivematica/MCPClient"

- name: "Template MCPClient /etc config"
  template:
    src: "etc_archivematica_MCPClient_clientConfig.conf.j2"
    dest: "/etc/archivematica/MCPClient/clientConfig.conf"
    backup: "yes"

- name: "Move archivematicaClientModules to /usr/lib/archivematica/MCPClient"
  command: "mv {{ archivematica_src_dir }}/archivematica/src/MCPClient/etc/archivematicaClientModules /usr/lib/archivematica/MCPClient/"
  args:
    creates: "/usr/lib/archivematica/MCPClient/archivematicaClientModules"
